/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cancerrlog;

import javax.swing.JOptionPane;

/**
 *
 * @author sandy
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radioLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        perimetroTF = new javax.swing.JTextField();
        radioTF = new javax.swing.JTextField();
        dimFracTF = new javax.swing.JTextField();
        suavidadTF = new javax.swing.JTextField();
        areaTF = new javax.swing.JTextField();
        texturaTF = new javax.swing.JTextField();
        concavidadTF = new javax.swing.JTextField();
        compacidadTF = new javax.swing.JTextField();
        puntConTF = new javax.swing.JTextField();
        simetriaTF = new javax.swing.JTextField();
        diagnosticoTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        pronosticoCompletoBTN = new javax.swing.JButton();
        pronosticoReducidoBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        radioLB.setText("Radio");

        jLabel3.setText("Textura");

        jLabel4.setText("Perímetro");

        jLabel5.setText("Área");

        jLabel6.setText("Suavidad");

        jLabel7.setText("Compacidad");

        jLabel8.setText("Concavidad");

        jLabel9.setText("Puntos Concavos");

        jLabel10.setText("Simetría");

        jLabel11.setText("Dimensión Fractal");

        jLabel12.setText("Diagnóstico");

        perimetroTF.setText("122.8");
        perimetroTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perimetroTFActionPerformed(evt);
            }
        });

        radioTF.setText("17.99");
        radioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTFActionPerformed(evt);
            }
        });

        dimFracTF.setText("0.07871");
        dimFracTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimFracTFActionPerformed(evt);
            }
        });

        suavidadTF.setText("0.1184");
        suavidadTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suavidadTFActionPerformed(evt);
            }
        });

        areaTF.setText("1001");
        areaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTFActionPerformed(evt);
            }
        });

        texturaTF.setText("10.38");
        texturaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texturaTFActionPerformed(evt);
            }
        });

        concavidadTF.setText("0.3001");
        concavidadTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concavidadTFActionPerformed(evt);
            }
        });

        compacidadTF.setText("0.2776");
        compacidadTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compacidadTFActionPerformed(evt);
            }
        });

        puntConTF.setText("0.1471");
        puntConTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntConTFActionPerformed(evt);
            }
        });

        simetriaTF.setText("0.2419");
        simetriaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simetriaTFActionPerformed(evt);
            }
        });

        diagnosticoTF.setEditable(false);
        diagnosticoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoTFActionPerformed(evt);
            }
        });

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        pronosticoCompletoBTN.setText("Pronosticar usando todas las variables");
        pronosticoCompletoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pronosticoCompletoBTNMouseClicked(evt);
            }
        });

        pronosticoReducidoBTN.setText("Pronosticar con dimensionalidad reducida");
        pronosticoReducidoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pronosticoReducidoBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioLB)
                                .addGap(53, 53, 53)
                                .addComponent(radioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(suavidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(areaTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(perimetroTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(texturaTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dimFracTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(compacidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(concavidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(puntConTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(simetriaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel12)
                        .addGap(25, 25, 25)
                        .addComponent(diagnosticoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pronosticoReducidoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(pronosticoCompletoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioLB)
                    .addComponent(compacidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texturaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(concavidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perimetroTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(puntConTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(simetriaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(suavidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimFracTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addComponent(pronosticoCompletoBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pronosticoReducidoBTN)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(diagnosticoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perimetroTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perimetroTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perimetroTFActionPerformed

    private void radioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTFActionPerformed

    private void dimFracTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimFracTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimFracTFActionPerformed

    private void suavidadTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suavidadTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suavidadTFActionPerformed

    private void areaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTFActionPerformed

    private void texturaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texturaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texturaTFActionPerformed

    private void concavidadTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concavidadTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concavidadTFActionPerformed

    private void compacidadTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compacidadTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compacidadTFActionPerformed

    private void puntConTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntConTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntConTFActionPerformed

    private void simetriaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simetriaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simetriaTFActionPerformed

    private void diagnosticoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosticoTFActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void pronosticoCompletoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pronosticoCompletoBTNMouseClicked
        float radio,textura,perimetro,area,suavidad,compacidad,concavidad,
            puntConcavos,simetria,dimFractal,reg_lineal,pronostico;
        try{
            radio=Float.valueOf(radioTF.getText());
            textura=Float.valueOf(texturaTF.getText());
            perimetro=Float.valueOf(perimetroTF.getText());
            area=Float.valueOf(areaTF.getText());
            suavidad=Float.valueOf(suavidadTF.getText());
            compacidad=Float.valueOf(compacidadTF.getText());
            concavidad=Float.valueOf(concavidadTF.getText());
            puntConcavos=Float.valueOf(puntConTF.getText());
            simetria=Float.valueOf(simetriaTF.getText());
            dimFractal=Float.valueOf(dimFracTF.getText());
            
            reg_lineal=(float) (7.35952+(2.04930*radio)+(-0.38473*textura)+
                    (0.07151*perimetro)+(-0.03980*area)+(-76.43227*suavidad)+
                    (1.46242*compacidad)+(-8.46870*concavidad)+
                    (-66.82176*puntConcavos)+(-16.27824*simetria)+
                    (68.33703*dimFractal));
            
            pronostico = (float) (1/(1+(Math.exp(-reg_lineal))));
            String resultado = pronostico>0.5? "Benigno":"Maligno";
            diagnosticoTF.setText(resultado);
        }
       catch(NumberFormatException nfe){ 
           JOptionPane.showMessageDialog(null,
                "Revisa que el formato de los datos sea válido");
       }
       
    }//GEN-LAST:event_pronosticoCompletoBTNMouseClicked

    private void pronosticoReducidoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pronosticoReducidoBTNMouseClicked
        float radio,textura,perimetro,area,suavidad,compacidad,concavidad,
            puntConcavos,simetria,dimFractal,reg_lineal,pronostico;
        try{
            radio=Float.valueOf(radioTF.getText());
            textura=Float.valueOf(texturaTF.getText());
            perimetro=Float.valueOf(perimetroTF.getText());
            area=Float.valueOf(areaTF.getText());
            suavidad=Float.valueOf(suavidadTF.getText());
            compacidad=Float.valueOf(compacidadTF.getText());
            concavidad=Float.valueOf(concavidadTF.getText());
            puntConcavos=Float.valueOf(puntConTF.getText());
            simetria=Float.valueOf(simetriaTF.getText());
            dimFractal=Float.valueOf(dimFracTF.getText());
            
            reg_lineal=(float) (28.5761+(-0.8238*radio)+(-0.3680*textura)+
                    (-45.6544*suavidad)+(-80.0723*puntConcavos)+
                    (-18.7889*simetria)+(42.1642*dimFractal));
            
            pronostico = (float) (1/(1+(Math.exp(-reg_lineal))));
            String resultado = pronostico>0.5? "Benigno":"Maligno";
            diagnosticoTF.setText(resultado);
        }
       catch(NumberFormatException nfe){ 
           JOptionPane.showMessageDialog(null,
                "Revisa que el formato de los datos sea válido");
       }
    }//GEN-LAST:event_pronosticoReducidoBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaTF;
    private javax.swing.JTextField compacidadTF;
    private javax.swing.JTextField concavidadTF;
    private javax.swing.JTextField diagnosticoTF;
    private javax.swing.JTextField dimFracTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField perimetroTF;
    private javax.swing.JButton pronosticoCompletoBTN;
    private javax.swing.JButton pronosticoReducidoBTN;
    private javax.swing.JTextField puntConTF;
    private javax.swing.JLabel radioLB;
    private javax.swing.JTextField radioTF;
    private javax.swing.JTextField simetriaTF;
    private javax.swing.JTextField suavidadTF;
    private javax.swing.JTextField texturaTF;
    // End of variables declaration//GEN-END:variables
}
